---
title: "R Notebook"
output: html_notebook
---

# CH1 Book:

__Continuous:__

cumulative distribution function = distribution function = F(x) = P(X<x) Probability that x is less than for equal to a specific number.


Survival function = $S_{x}X$ = 1-F(x) = the probability that x is greater than a specific number.

pdf = f(x) = derivative of the cumulative function, or the negative of the derivative of the survival function. Values with higher pdfs are more likely to occur than values with lower pdfs. 

F(b)=$\int_{-\infty}^{b}$, S(b) = $\int_{b}^{\infty}$

__Discrete:__

pmf = $p_{x}x$ = probability at a distinct point when it is not zero, used for discrete data.

F(x) = $\sum_{y \le x} p(y)$ and $S(x)=\sum_{y>x} p(y)$

__Hazard Rate:__

hazard rate = force of mortality = $h_{x}x$ = is the ratio of the density and survival function = $f_{x}(x)/S_{x}(x)$ Interpreted as the probability density at x given that the argument will be at least x.

$S(b) = e^{-\int_{0}^{b}h(x)dx}$

$h_{x}(x) = -S'(x)/S(x)=-d\ lnS(x)/dx$

__Moments:__

The kth raw moment of a random variable is the expected average value of the kth power of that variable, provided that it exists. $E(X^{k})$

continuous: $\mu'_{k}$=$E(X^{k})$=$\int_{-\infty}^{\infty}x^{k}f(x)dx$

discrete: $\sum_{j} x^{k}_{j}p(x_{j})$

kth central moment = expected value of the kth power of the standard deviation of the variable from its mean. 
$E[(X-\mu)^{k}]$

Second central moment = variance, Ratio of the standard deviation to the mean = coefficient of variation = $\frac{\sigma}{\mu}$

Ratio of the third central moment to the cube of the standard deviation is the skewness = $y_{1}=\mu_{3}/\sigma^{3}$

Ratio of the fourth central moment to fourth power of the standard deviation is kurtosis = $y_{2}=\mu_{4}/\sigma^{4}$

calculating

continuous: $\int_{-\infty}^{\infty}(x-\mu)^{k}f(x)dx$

discrete: $\sum_{j}(x_{j}-\mu)^{k}p(x_{j})$

__Excess Loss Variable:__

left truncated and shifted variable

mean excess loss function is a given value of x, given that it is greater than d. $e_{x}(d)=e(d)=E(Y^{p})=E(X-d|X>d)$ Also called mean residual life function or left truncated and shifted variable. Left truncated because any value below d is not observed, shifted because d is subtracted from the remaining values. 

continuous: $e^{k}_{x}(d)=\frac{\int_{d}^{\infty}(x-d)^{k}f(x)dx}{1-F(d)}$

discrete: $\frac{\sum_{x_{j}>d}(x_{j}-d)^{k}p(x_{j})}{1-F(d)}$


__left censored and shifted variable:__

$Y^{L}=(X-d)_{+}=$ 0 if $X\le d$, X-d if $X>d$

values below d are not ignored but are set equal to 0. In the left truncated and shifted variable it is per payment where the variable exists only when a payment is made. In left censored and shifted it is a per loss which takes on the value 0 whenever a loss produces no payment. 

continuous: $E[(X-d)^{k}_{+}]=\int_{d}^{\infty}(x-d)^{k}f(x)dx$

discrete: $\sum_{x_{j}>d}(x_{j}-d)^{k}p(x_{j})$


__limited loss variable:__

right censored variable

$Y=X \wedge u$= X if $X<u$, u if $X\ge u$

It is right censored because values above u are set equal to u. It is a policy limit that sets a maximum on the benefit to be paid. 

Deductible and policy limit at the same price is the same as full coverage. $(X-d)_{+} + (X \wedge d)=X$

continuous: $E[(X \wedge u)^{k}]=\int_{-\infty}^{u} x^{k}f(x)dx+u^{k}[1-F(u)]$

discrete: $E[(X \wedge u)^{k}]=\sum_{x_{j}\le u} x^{k}_{j}p(x_{j})+u^{k}[1-F(u)]$

__Percentiles:__

The percentile function is the inverse of the distribution function. Quantile uses values between 0 and 1, percentile uses values between 0 and 100. 70th percentile = .7 quantile.

Only time it is not defined is when the distribution function is constant at a value of p over a range of values of the random variable.

50th percentile = $\pi_{.5}$ = median


__Generating Functions and Sums of Random Variable:__

If $S_{k}$ is a random variable which represents the sum of all claims then:

$E(S_{K})$=$E(X_{1})+E(X_{2})+...+E(X_{k})$

if $X_{1}...X_{k}$ are independent, $Var(S_{k})=Var(X_{1})+Var(X_{2})+...+Var(X_{k})$

if $X_{1}...X_{k}$ are independent and their first two moments meet certain conditions, $lim_{k \to \infty}[S_{k}-E(S_{k})]/\sqrt{Var(S_{k})}$ has a normal distribution with mean 0 and variance 1.

When working with a sequence of random variables the limit used in the theorem is called the convergence in distribution. Probabilities of sums of random variables can often be approximated by those from the normal distribution. 

__Moment Generating Function:__

MGF = $M_{x}(z)=E(e^{zX})$ for all z for which the expected value exists.

Probability generating function, pgf=$P_{X}(z)=E(z^{X})$ for all z for which the expectation exists

$M_{x}(z)=P_{x}(e^{z})$ and $P_{x}(z)=M_{x}(ln\ z)$

Often the mgf is used for continuous random variables, and the pgf for discrete random variables. Two random variables with different distribution functions cannot have the same mgf or pgf. The following aid works with sums of random variables. There is a one to one correspondence between a random variable's distribution function and its mgf and pgf.

__Combining them for $S_{k}$:__

if $S_{k}=x_{1}+...+x_{k}$ where x's are independent and random variables then:

$M_{s_{k}}(z)=\Pi_{j=1}^{k}M_{X_{j}}(z)$ and $P_{s_{k}}(z)=\Pi_{j=1}^{k}P_{X_{j}}(z)$

$M_{s_{k}}(z)=E(e^{zS_{k}})=E(e^{z(x1+x2+...+x_{z})})$

 __Tails:__
 
 If all positive moments exist then it is an indication of a light right tail. If only positive moments up to a certain point exist then it is evidence of a heavy right tail. 
 
 If a distribution does not have all its positive moments, then it does not have a MGF. If a distribution has all its positive moments, it still might not have a mgf. 



To check which distribution has a heavier tail when they have the same mean is to use the ratio of the two survival functions as they approach infinity. Can also use density functions instead of survival functions. 

Distributions with decreasing hazard rate functions have heavy tails. Distributions with increasing hazard rate functions have light tails. A distribution has a lighter tail than another is its hazard rate function is increasing at a faster rate. 

If the mean excess loss function is increasing in d, the distribution is considered a heavy tail. If the mean excess loss function is decreasing in d, it is considered to have a light tail.

__Measures of Risk:__

key risk indicators- level of risk, often described by one number.

Value at Risk (VaR)- a quantile of the distribution of aggregate losses. 

Tail Value at Risk (TVaR)- more informative and useful measure of VaR. 

risk measure- gives a single number that is intended to quantify the risk exposure. Denoted $\rho(X)$. It is the amount of assets required to protect against adverse outcomes of risk X. 

Coherent Risk Measure: has the following properties for two loss random variables

1) Subadditivity: $\rho(X+Y)\le \rho(x) + \rho(y)$

2) Monotonicity: if X<Y for all possible outcomes, then $\rho(X)\le \rho(Y)$

3) Positive Homogeneity: for any positive constant c, $\rho(cX)=c\rho (X)$

4) Translation Invariance: for any constant c, $\rho (X+c)=\rho (X)+c$

Subadditivity states that two risks combined will not be greater than for the risks treated separately, there should be some diversification benefit from combining risks. Monotonicity means that if one risk always has greater losses than another risk under all circumstances, the risk measure (capital required to support it) should always be greater. Positive homogeneity means that the risk measure and capital required to support it is independent of the currency in which the risk is measured. Doubling the exposure to a particular risk requires double the capital, no diversification benefit. Translation invariance means that there is no additional risk (capital required to support it) for an additional risk for which there is not additional uncertainty.   

VaR- Is not coherent because it does not cover subadditivity. It is the threshold percentage that the company can cover all possible loses. For a 95% quantile of VaR there is only a 5% chance of lossed exceeding the VaR value.

VaR is used extensively in financial risk management of trading risk over a fixed (usually relatively short) time period. If distributions of gains or losses are restricted to the normal distribution then VaR is coherent. However, the normal distribution is generally not used for describing insurance losses.

TVaR- Is coherent- the average of all VaR values above the security level p.

$TVaR_{p}(X)=\frac{\int_{p}^{1}VaR_{u}(X)du}{1-p}$

or $VaR_{p}(X)+e(\pi _{p})$

-$e(\pi _{p})$ = mean excess loss function

















